services:
  debian-desktop:
    image: liuxcserver/desktop-docker:latest
    container_name: debian-desktop
    hostname: debian-desktop
    network_mode: bridge
    # 环境变量配置
    environment:
      - USER_NAME=appuser  # 默认用户,可修改
      - USER_PASS=123456  # 默认用户,可修改
      - VNC_PASS=123456  # 默认vnc密码, 可修改
      - LANG=zh_CN.UTF-8
    # 端口映射
    ports:
      - "46080:6080"   # Web 访问 (noVNC)
    # 持久化用户home目录
    volumes:
      - /vol1/1000/space/docker/debian-desktop/config:/config
    # 重启策略
    restart: unless-stopped