[supervisord]
nodaemon=true

[program:dbus]
command=/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --syslog-only
user=root
autorestart=true

[program:xfce4]
command=/usr/bin/startxfce4
user=user
environment=HOME="/home/user",USER="user"
autorestart=true

[program:xrdp]
command=/usr/sbin/xrdp -nodaemon
user=root
autorestart=true

[program:kasmvnc]
# 启动 KasmVNC，监听 6901 端口
command=/usr/bin/kasmvncserver :1 -geometry 1920x1080 -depth 24
user=user
environment=HOME="/home/user",USER="user",LIBVA_DRIVER_NAME="iHD"
autorestart=true